#ifndef SECURE_CLOUD_STORAGE_DIGITALSIGNATUREMANAGER_H
#define SECURE_CLOUD_STORAGE_DIGITALSIGNATUREMANAGER_H


class DigitalSignatureManager {

};


#endif //SECURE_CLOUD_STORAGE_DIGITALSIGNATUREMANAGER_H
